blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>/',views.ArchivesView.as_view(),name='archives'),
    path('category/<int:pk>',views.CategoryView.as_view(),name='category'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/post/<int:post_pk>/',views.post_comment,name='post_comment'),
]

myblog2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('',include('comments.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# 导入 reverse 函数
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


class Category(models.Model):
    """
    Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    Django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100,verbose_name='分类')

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100,verbose_name='标签')

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField(max_length=70,verbose_name='标题')

    # 文章正文，我们使用了 TextField。
    # 使用 TextField 来存储大段文本。
    body = models.TextField(verbose_name='正文')

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField(verbose_name='创建时间')
    modified_time = models.DateTimeField(verbose_name='修改时间')

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True,verbose_name='摘要')

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    category = models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='分类')
    tags = models.ManyToManyField(Tag, blank=True,verbose_name='标签')

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者')



    #复写save方法用于自动提取文章摘要
    def save(self,*args,**kwargs):
        if not self.excerpt:
            #实例化Markdown类，渲染body文本
            md = markdown.Markdown(extensions=[
                                                'markdown.extensions.extra',
                                                'markdown.extensions.codehilite',

            ])
            #去掉html标签，截取前30个字符给摘要
            self.excerpt = strip_tags(md.convert(self.body))[:30]
        #保存到数据库中
        super(Post, self).save(*args,**kwargs)

    # 阅读统计量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])


    def __str__(self):
        return self.title


    # 自定义 get_absolute_url 方法
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post',on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Post,Category
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView,DetailView
#from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger


# Create your views here.
#from django.http import HttpResponse
#每一个视图函数都有它对应的类的对应视图
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 3

def index(request):
    post_list = Post.objects.all() #.order_by('-created_time')#已在models中进行了排序
    return render(request, 'blog/index.html', context={'post_list': post_list})


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self,request,*args,**kwargs):
        #调用父类get方法后才能获得self.object属性即为访问的文章
        response = super(PostDetailView, self).get(request,*args,**kwargs)

        #文章（self.object）阅读量
        self.object.increase_views()

        return response

    def get_object(self, queryset=None):
        # 对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          'markdown.extensions.toc',
                                      ])
        return post

    def get_context_data(self, **kwargs):
        #将post传递给模板，同时将评论表单，post下的评论列表传递给模板
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context



def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    #调用阅读量函数
    post.increase_views()

    #引入Markdown标记语言进行文本编辑
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    #获取本篇文章下的全部评论
    comment_list = post.comment_set.all()
    #将下列三个作为变量传给detail.html渲染
    context = {'post':post,
               'form':form,
               'comment_list':comment_list
    }


    return render(request, 'blog/detail.html', context=context)

class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)

def archives(request,year,month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request,'blog/index.html',context={'post_list':post_list})

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="{{ form.name.id_for_label }}">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.url.id_for_label }}">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="{{ form.text.id_for_label }}">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ comment_list|length }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                    {{ comment.text }}
                                </div>
                            </li>
                            {% empty %}
                                  暂无评论
                            {% endfor %}
                        </ul>
                    </div>
                </section>
{% endblock main %}

{#{% block toc %}#}
{#                <div class="widget widget-content">#}
{#                    <h3 class="widget-title">文章目录</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">教程特点</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">谁适合这个教程</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">在线预览</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">资源列表</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">获取帮助</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="widget widget-recent-posts">#}
{#                    <h3 class="widget-title">最新文章</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django 博客开发入门教程：前言</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">部署 Django 博客</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="widget widget-archives">#}
{#                    <h3 class="widget-title">归档</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">2017 年 5 月</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">2017 年 4 月</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">2017 年 3 月</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-category">#}
{#                    <h3 class="widget-title">分类</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python 教程 <span class="post-count">(11)</span></a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{##}
{#                <div class="widget widget-tag-cloud">#}
{#                    <h3 class="widget-title">标签云</h3>#}
{#                    <ul>#}
{#                        <li>#}
{#                            <a href="#">Django</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Python</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Java</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">笔记</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">文档</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">AngularJS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">CSS</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">JavaScript</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">Snippet</a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="#">jQuery</a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </div>#}
{#                <div class="rss">#}
{#                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#                </div>#}
{#{% endblock toc %}#}

templates/blog/index.html
{% extends 'base.html' %}

{% load staticfiles %}


            {% block main %}
                {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="{% url 'comments:post_comment' post.pk %}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div class="no-post">暂时还没发表文章！</div>
                {% endfor %}
{#                简单分页效果#}
                {% if is_paginated %}
                <div class="pagination-simple">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}
                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                {% endif %}

{#                <div class="pagination">#}
{#                    <ul>#}
{#                        <li><a href="">1</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">4</a></li>#}
{#                        <li><a href="">5</a></li>#}
{#                        <li class="current"><a href="">6</a></li>#}
{#                        <li><a href="">7</a></li>#}
{#                        <li><a href="">8</a></li>#}
{#                        <li><a href="">...</a></li>#}
{#                        <li><a href="">11</a></li>#}
{#                    </ul>#}
{#                </div>#}
            {% endblock main %}